type: operator
category: projection
name: $meta
description: Returns metadata associated with documents in the result set, particularly useful for accessing text search scores and other query execution metadata.
syntax: '{ $meta: "<meta_data_keyword>" }'
parameters:
  - name: meta_data_keyword
    type: string
    required: true
    description: 'The type of metadata to return: "textScore" for text search relevance scores'
examples:
  items:
    - title: Get text search scores
      description: Return text search relevance scores with query results
      query: 'db.articles.find({ $text: { $search: "mongodb database" } }, { title: 1, score: { $meta: "textScore" } })'
      output:
        value: Documents with title field and search relevance score
    - title: Sort by text score
      description: Sort text search results by relevance score
      query: 'db.articles.find({ $text: { $search: "mongodb database" } }, { title: 1, score: { $meta: "textScore" } }).sort({ score: { $meta: "textScore" } })'
      output:
        value: Documents sorted by text search relevance, highest score first
    - title: Filter by minimum score
      description: Return only documents with text score above threshold
      query: 'db.articles.aggregate([{ $match: { $text: { $search: "mongodb database" } } }, { $addFields: { score: { $meta: "textScore" } } }, { $match: { score: { $gte: 0.5 } } }])'
      output:
        value: Documents with text search score of 0.5 or higher
related:
  - reference: /reference/operator/text
  - reference: /reference/operator/sort